export const getRegionJson = reg => ({
    'NWS': NSW,
    'Tessin': TESSIN,
    'Romandie': ROMANDIE,
    'OS': OSTSCHWEIZ
})[reg] || NSW;

export const TESSIN = [];
export const ROMANDIE = [];

export const NSW = [
    {
        Firma: "a. hartrodt (Schweiz) AG",
        Adresse: "Hofackerstrasse 40A",
        PLZ: 4132,
        Ort: "Muttenz",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.hartrodt.com",
        Yousty: ""
    },
    {
        Firma: "Abacus Shipping Ltd",
        Adresse: "Neuhausstrasse 1",
        PLZ: 4019,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.abacus-shipping.ch",
        Yousty: ""
    },
    {
        Firma: "AIT Worldwide Logistics Switzerland AG",
        Adresse: "Genua-Strasse 11",
        PLZ: 4142,
        Ort: "Münchenstein",
        Kontaktperson: "Sabrina Rolli",
        Telefon: "061/337 43 37",
        Mail: "sabrina.rolli@fiege.com",
        Internet: "www.aitworldwide.com",
        Yousty: ""
    },
    {
        Firma: "Atlantic Forwarding Ltd.",
        Adresse: "Grosspeteranlage 29",
        PLZ: 4052,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.atlanticforwarding.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/8857229-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-ausbildungsverbund-spedlogswiss-nordwestschweiz"
    },
    {
        Firma: "Ausbildungsverbund SPEDLOGSWISS Nordwestschweiz",
        Adresse: "Elisabethenstrasse 44",
        PLZ: 4002,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.abvnws.ch",
        Yousty: ""
    },
    {
        Firma: "Balimpex AG",
        Adresse: "Frohburgerstrasse 21",
        PLZ: 4132,
        Ort: "Muttenz",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.balimpex.ch",
        Yousty: ""
    },
    {
        Firma: "Bertschi AG",
        Adresse: "Hutmattstrasse 22",
        PLZ: 5724,
        Ort: "Dürrenäsch",
        Kontaktperson: "Sabrina Gränacher",
        Telefon: "062/767 67 55",
        Mail: "sabrina.graenacher@bertschi.com",
        Internet: "www.bertschi.com",
        Yousty: ""
    },
    {
        Firma: "Birsterminal AG",
        Adresse: "Hafenstrasse 54",
        PLZ: 4127,
        Ort: "Birsfelden",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.birsterminal.ch",
        Yousty: ""
    },
    {
        Firma: "BPS Speditions Service Basel AG",
        Adresse: "Dürrenhübelstrasse 7",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.bps-spedition.ch",
        Yousty: ""
    },
    {
        Firma: "BTG Suisse AG",
        Adresse: "Salinenstrasse 61",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.btg-suisse.ch",
        Yousty: ""
    },
    {
        Firma: "Camion Transport AG",
        Adresse: "St. Jakobs-Strasse 228",
        PLZ: 4052,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.camiontransport.ch",
        Yousty: ""
    },
    {
        Firma: "Central Station AG",
        Adresse: "Rittergasse 35",
        PLZ: 4010,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.4plcs.com",
        Yousty: ""
    },
    {
        Firma: "Dachser Spedition AG",
        Adresse: "Langenhagstrasse 6",
        PLZ: 4127,
        Ort: "Birsfelden",
        Kontaktperson: "Monica Nuno",
        Telefon: "061/315 12 21",
        Mail: "monica.nuno@dachser.com",
        Internet: "www.dachser.com",
        Yousty: ""
    },
    {
        Firma: "Dachser Spedition AG",
        Adresse: "Südstrasse 33",
        PLZ: 3250,
        Ort: "Lyss",
        Kontaktperson: "Sabrina Stauffer",
        Telefon: "032/389 02 21",
        Mail: "sabrina.stauffer@dachser.com",
        Internet: "www.dachser.com",
        Yousty: ""
    },
    {
        Firma: "Dachser Spedition AG Air & Sea Logistics",
        Adresse: "Sternenhofstrasse 15a",
        PLZ: 4153,
        Ort: "Reinach",
        Kontaktperson: "Vanessa Palumbo",
        Telefon: "061/716 16 02",
        Mail: "vanessa.palumbo@dachser.com",
        Internet: "www.dachser.com",
        Yousty: ""
    },
    {
        Firma: "Danser Switzerland AG",
        Adresse: "Südquaistrasse 14",
        PLZ: 4057,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.danser.ch",
        Yousty: ""
    },
    {
        Firma: "DHL Logistics (Schweiz) AG",
        Adresse: "St. Jakobsstrasse 222",
        PLZ: 4002,
        Ort: "Basel",
        Kontaktperson: "Nadia Vogt",
        Telefon: "061/315 95 20",
        Mail: "nadia.vogt@dhl.com",
        Internet: "www.dhl.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12625267-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-pratteln-bl-dhl-logistics-schweiz-ag"
    },
    {
        Firma: "DSV Air + Sea AG",
        Adresse: "Viaduktstrasse 42",
        PLZ: 4052,
        Ort: "Basel",
        Kontaktperson: "Silke Meier",
        Telefon: "061/337 48 51",
        Mail: "silke.meier@ch.dsv.com",
        Internet: "www.dsv.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12658351-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-dsv-air-sea-ag?uid=2392411"
    },
    {
        Firma: "DSV Air + Sea AG",
        Adresse: "Industriering 17",
        PLZ: 3250,
        Ort: "Lyss",
        Kontaktperson: "Patricia Russo",
        Telefon: "044/829 40 52",
        Mail: "patricia.russo@dsv.com",
        Internet: "www.dsv.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12658351-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-dsv-air-sea-ag?uid=2392411"
    },
    {
        Firma: "DSV Logistics SA",
        Adresse: "Salinenstrasse 61",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Salome Huber",
        Telefon: "061/690 73 92",
        Mail: "salome.huber@dsv.com",
        Internet: "www.dsv.com",
        Yousty: ""
    },
    {
        Firma: "EMC Partner AG",
        Adresse: "Baselstrasse 160",
        PLZ: 4242,
        Ort: "Laufen",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.emc-partner.com",
        Yousty: ""
    },
    {
        Firma: "Eurosped AG",
        Adresse: "Niderfeldstrasse 5",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.eurosped.ch",
        Yousty: ""
    },
    {
        Firma: "FedEx Express Swiss Post GmbH",
        Adresse: "Amsleracherweg 8",
        PLZ: 5033,
        Ort: "Buchs",
        Kontaktperson: "Cornelia Rappo",
        Telefon: "062/561 24 05",
        Mail: "cornelia.rappo@fedex.com",
        Internet: "www.tntswisspost.ch",
        Yousty: ""
    },
    {
        Firma: "Fiege Logistik (Schweiz) AG",
        Adresse: "Genua-Strasse 11",
        PLZ: 4142,
        Ort: "Münchenstein",
        Kontaktperson: "Sabrina Rolli",
        Telefon: "061/337 43 37",
        Mail: "sabrina.rolli@fiege.com",
        Internet: "www.fiege.ch",
        Yousty: ""
    },
    {
        Firma: "Fracht AG",
        Adresse: "Birsigstrasse 79",
        PLZ: 4011,
        Ort: "Basel",
        Kontaktperson: "Cathy Dusé",
        Telefon: "061/287 95 64",
        Mail: "c.duse@frachtag-bs.ch",
        Internet: "www.frachtag.ch",
        Yousty: ""
    },
    {
        Firma: "Fröde Möbelspedition AG",
        Adresse: "Signalstrasse 101",
        PLZ: 4058,
        Ort: "Basel",
        Kontaktperson: "Christof Lützelschwab",
        Telefon: "061/690 66 52",
        Mail: "christof.luetzelschwab@froede.com",
        Internet: "www.froede.ch",
        Yousty: ""
    },
    {
        Firma: "FT Logistics AG",
        Adresse: "Kästeliweg 6",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Rupen Elmayan",
        Telefon: "061/826 94 44",
        Mail: "relmayan@ft-logistics.ch",
        Internet: "www.ft-logistics.ch",
        Yousty: ""
    },
    {
        Firma: "Gebrüder Weiss AG",
        Adresse: "Dürrenhübelstrasse 4",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Emel Alkan",
        Telefon: "058/458 50 48",
        Mail: "emel.alkan@gw-world.com",
        Internet: "www.gw-world.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/1360-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-pratteln-bl-gebrueder-weiss-ag"
    },
    {
        Firma: "Geisseler Cargo Logistik AG",
        Adresse: "Im Wannenboden 8",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.geisseler.ch",
        Yousty: ""
    },
    {
        Firma: "General Transport AG",
        Adresse: "St. Albanring 254",
        PLZ: 4052,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.general-transport.com",
        Yousty: ""
    },
    {
        Firma: "Hapag-Lloyd (Schweiz) AG",
        Adresse: "Südquaistrasse 14",
        PLZ: 4057,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.hlcl.com",
        Yousty: ""
    },
    {
        Firma: "InTraLog Hermes AG",
        Adresse: "Niderfeldstrasse 5",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.intraloghermes.ch",
        Yousty: ""
    },
    {
        Firma: "ITS International Transport and Shipping Ltd.",
        Adresse: "Christoph Merian Ring 29",
        PLZ: 4153,
        Ort: "Reinach",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.its-transport.ch",
        Yousty: ""
    },
    {
        Firma: "JAS Forwarding SA",
        Adresse: "P.O. Box 32",
        PLZ: 4030,
        Ort: "Basel-Flughafen",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.jas.com",
        Yousty: ""
    },
    {
        Firma: "KGH Customs Services Schweiz AG",
        Adresse: "Salinenstrasse 63",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.kghcustoms.com",
        Yousty: ""
    },
    {
        Firma: "Kühne & Nagel AG",
        Adresse: "Bäumlimattstrasse 12",
        PLZ: 4313,
        Ort: "Möhlin",
        Kontaktperson: "Philip Weinmann",
        Telefon: "061/465 66 35",
        Mail: "philip.weinmann@kuehne-nagel.com",
        Internet: "www.kuehne-nagel.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/10690489-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-moehlin-ag-kuehne-nagel-ag"
    },
    {
        Firma: "Lagerhäuser Aarau AG",
        Adresse: "Aegerten 1",
        PLZ: 5503,
        Ort: "Schafisheim",
        Kontaktperson: "Anja Woellner",
        Telefon: "062/885 32 87",
        Mail: "a.woellner@la-aarau.ch",
        Internet: "www.la-aarau.ch",
        Yousty: ""
    },
    {
        Firma: "Lamprecht Transport AG",
        Adresse: "Peter Merian-Strasse 48",
        PLZ: 4002,
        Ort: "Basel",
        Kontaktperson: "Alain Tanner",
        Telefon: "061/284 72 92",
        Mail: "alain.tanner@lamprecht.ch",
        Internet: "www.lamprecht.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/8832388-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-lamprecht-transport-ag"
    },
    {
        Firma: "M&M Militzer & Münch AG",
        Adresse: "Hofackerstrasse 77",
        PLZ: 4132,
        Ort: "Muttenz",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.mumnet.com",
        Yousty: ""
    },
    {
        Firma: "M+R Spedag Group AG",
        Adresse: "Kriegackerstrasse 91",
        PLZ: 4132,
        Ort: "Muttenz",
        Kontaktperson: "Martine Sanchez",
        Telefon: "058/677 95 20",
        Mail: "martine.sanchez@mrspedag.com",
        Internet: "www.mrspedag.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12666851-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-muttenz-bl-m-r-spedag-group-ag?uid=2389062"
    },
    {
        Firma: "MSC Mediterranean Shipping Agency AG",
        Adresse: "Steinentorstrasse 39",
        PLZ: 4002,
        Ort: "Basel",
        Kontaktperson: "Suzy Monnier",
        Telefon: "061/555 65 13",
        Mail: "suzy.monnier@msc.com",
        Internet: "www.mscgva.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/8849933-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-msc-mediterranean-shipping-agency-ag"
    },
    {
        Firma: "Müller-Gysin AG",
        Adresse: "Barcelona-Strasse 8",
        PLZ: 4023,
        Ort: "Basel",
        Kontaktperson: "Anita Cavelti",
        Telefon: "061/337 61 11",
        Mail: "anita.cavelti@muellergysin.ch",
        Internet: "www.muellergysin.ch",
        Yousty: ""
    },
    {
        Firma: "Nauta SA",
        Adresse: "Grüssenhölzliweg 3",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Franziska Melillo",
        Telefon: "061/337 31 69",
        Mail: "franziska.melillo@nauta.ch",
        Internet: "www.nauta.ch",
        Yousty: ""
    },
    {
        Firma: "Nord Transport AG",
        Adresse: "Talstrasse 45b",
        PLZ: 4144,
        Ort: "Arlesheim",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.nordtransport.ch",
        Yousty: ""
    },
    {
        Firma: "Otto Schmidt AG",
        Adresse: "Dürrenhüberlstrasse 7",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Demian Ingold",
        Telefon: "061/690 90 84",
        Mail: "d.ingold@otto-schmidt.ch",
        Internet: "www.otto-schmidt.ch",
        Yousty: ""
    },
    {
        Firma: "PESA AG",
        Adresse: "Salinenstrasse 59",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Hedi Grieshaber",
        Telefon: "061/404 44 42",
        Mail: "hgrieshaber@pesa.global",
        Internet: "www.pesa.global",
        Yousty: ""
    },
    {
        Firma: "Post CH AG, PostLogistics AG",
        Adresse: "Post-Passage 11",
        PLZ: 4051,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.post.ch",
        Yousty: ""
    },
    {
        Firma: "Rhenus Alpina AG",
        Adresse: "Wiesendamm 4",
        PLZ: 4019,
        Ort: "Basel",
        Kontaktperson: "Alexandra Hermkes",
        Telefon: "061/639 34 90",
        Mail: "alexandra.hermkes@ch.rhenus.com",
        Internet: "www.rhenus.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/10057282-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-rhenus-alpina-ag"
    },
    {
        Firma: "Sara Transporte AG",
        Adresse: "Nägeliweg 2",
        PLZ: 5313,
        Ort: "Klingnau",
        Kontaktperson: "Nehar Alijovi",
        Telefon: "056/282 11 81",
        Mail: "Nehar.Alijovi@sara-transporte.ch",
        Internet: "www.sara-transporte.ch",
        Yousty: ""
    },
    {
        Firma: "Savino Del Bene AG",
        Adresse: "Hohenrainstrasse 10",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.savinodelbene.com",
        Yousty: ""
    },
    {
        Firma: "Schenker Schweiz AG",
        Adresse: "Hardstrasse 11",
        PLZ: 5074,
        Ort: "Eiken",
        Kontaktperson: "Sabrina Köpke\nStefan Simmen",
        Telefon: "058/589 52 32\n058/589 53 62",
        Mail: "sabrina.koepke@dbschenker.com  stefan.simmen@dbschenker.com",
        Internet: "www.dbschenker.com/ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/9553028-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-schenker-schweiz-ag"
    },
    {
        Firma: "Schenker Schweiz AG",
        Adresse: "Steigerhubelstrasse 3",
        PLZ: 3000,
        Ort: "Bern 5",
        Kontaktperson: "Diana Manco",
        Telefon: "058/589 50 70",
        Mail: "diana.manco@dbschenker.com",
        Internet: "www.dbschenker.com/ch",
        Yousty: ""
    },
    {
        Firma: "Schneider & Cie. AG",
        Adresse: "Solothurnerstrasse 48",
        PLZ: 4002,
        Ort: "Basel",
        Kontaktperson: "Miriam Ziltener",
        Telefon: "061/365 96 76",
        Mail: "mziltener@schneider-transport.com",
        Internet: "www.schneider-transport.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12628233-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-schneider-cie-ag"
    },
    {
        Firma: "Streck Transport AG",
        Adresse: "Industriestrasse 30",
        PLZ: 4313,
        Ort: "Möhlin",
        Kontaktperson: "Hendrik Caspar",
        Telefon: "061/855 11 01",
        Mail: "hendrik.caspar@streck.ch",
        Internet: "www.streck.ch",
        Yousty: ""
    },
    {
        Firma: "Trans Maritime AG",
        Adresse: "Rheinfelderstrasse 12",
        PLZ: 4127,
        Ort: "Birsfelden",
        Kontaktperson: "Agnes Jütte",
        Telefon: "061/319 55 06",
        Mail: "a.juette@tmbs.ch",
        Internet: "www.transmaritime.ch",
        Yousty: ""
    },
    {
        Firma: "Transfreight AG",
        Adresse: "Leimgrubenweg 6",
        PLZ: 4023,
        Ort: "Basel",
        Kontaktperson: "Daniela Moscatiello",
        Telefon: "061/337 49 43",
        Mail: "moscatiello.daniela@transfreight.ch",
        Internet: "www.transfreight.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12675575-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-basel-bs-transfreight-ag?uid=2393104"
    },
    {
        Firma: "TS Transport-Service AG",
        Adresse: "Mailand-Strasse 31",
        PLZ: 4053,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.transport-service.ch",
        Yousty: ""
    },
    {
        Firma: "Ultra-Brag AG",
        Adresse: "Südquaistrasse 55",
        PLZ: 4019,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.ultra-brag.ch",
        Yousty: ""
    },
    {
        Firma: "Vector Logistics AG",
        Adresse: "Lohagstrasse 14",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Gunhild Wolf",
        Telefon: "061/815 90 98",
        Mail: "guni.wolf@vector-logistics.ch",
        Internet: "www.vector-logistics.ch",
        Yousty: ""
    },
    {
        Firma: "VL Verzollung & Logistik AG",
        Adresse: "St. Jakobs-Strasse 222",
        PLZ: 4020,
        Ort: "Basel",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.vl-verzollunglogistik.ch",
        Yousty: ""
    },
    {
        Firma: "Waterside Logistics",
        Adresse: "Bodenackerstrasse 39",
        PLZ: 4657,
        Ort: "Dulliken",
        Kontaktperson: "Mohamed Kobeissi",
        Telefon: "062/849 46 46",
        Mail: "m.k@water-side.ch",
        Internet: "www.waterside.ch",
        Yousty: ""
    },
    {
        Firma: "World Courier (Switzerland) SA",
        Adresse: "Cargo Terminal",
        PLZ: 4030,
        Ort: "Basel-Flughafen",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.worldcourier.com",
        Yousty: ""
    },
    {
        Firma: "Ziegler (Schweiz) AG",
        Adresse: "Netzibodenstrasse 23c",
        PLZ: 4133,
        Ort: "Pratteln",
        Kontaktperson: "Franziska Vosseler",
        Telefon: "061/818 53 36",
        Mail: "franziska.vosseler@ziegler.ch",
        Internet: "www.ziegler.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/8873510-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-pratteln-bl-ziegler-schweiz-ag"
    },
    {
        Firma: "Zoll-Flex GmbH",
        Adresse: "Rüchligweg 101",
        PLZ: 4125,
        Ort: "Riehen",
        Kontaktperson: "Ausbildungsverbund",
        Telefon: "061/205 98 06",
        Mail: "teamabv@spedlogswiss.com",
        Internet: "www.zoll-flex.ch",
        Yousty: ""
    }
]

export const OSTSCHWEIZ = [
    {
        Firma: "Bolloré Logistics Suisse SA",
        Adresse: "Hagenholzstrasse 85",
        Ort: "Zürich",
        Kontaktperson: "Frau Laura Bättig",
        Telefon: "043 411 48 05",
        Mail: "laura.baettig@bollore.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12673369-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-zuerich-zh-bollore-logistics-suisse-sa?uid=2361963",
        Internet: "www.bollore.com",
        PLZ: "8050"
    },
    {
        Firma: "BPS Speditions-Service AG",
        Adresse: "Wanistrasse 5",
        Ort: "Pfungen",
        Kontaktperson: "Herr Dieter Brocks",
        Telefon: "052 305 04 04",
        Mail: "brocks@bps-spedition.ch",
        Yousty: "",
        Internet: "www.bps-spedition.ch",
        PLZ: "8422"
    },
    {
        Firma: "Cargocare Global AG",
        Adresse: "Grindelstrasse 6",
        Ort: "Bassersdorf",
        Kontaktperson: "Herr Sandro Nägeli",
        Telefon: "044 866 31 36",
        Mail: "sandro.naegeli@cargocare.ch",
        Yousty: "",
        Internet: "www.cargocare.ch",
        PLZ: "8303"
    },
    {
        Firma: "CEVA Logistics Switzerland GmbH",
        Adresse: "Oberfeldstrasse 14",
        Ort: "Kloten",
        Kontaktperson: "Herr Florian Funke",
        Telefon: "043 547 01 00",
        Mail: "florian.funke@cevalogistics.com",
        Yousty: "",
        Internet: "www.cevalogistics.com",
        PLZ: "8302"
    },
    {
        Firma: "CLG AG",
        Adresse: "Fracht Ost, Postfach 109",
        Ort: "Zürich-Flughafen",
        Kontaktperson: "Herr Patrick Leuenberger",
        Telefon: "043 816 01 00",
        Mail: "patrick.leuenberger@clg.ch",
        Yousty: "",
        Internet: "www.clg.ch",
        PLZ: "8058"
    },
    {
        Firma: "Commodity Supplies AG",
        Adresse: "Roosstrasse 53, Postfach 172",
        Ort: "Wollerau",
        Kontaktperson: "Frau Corinne Binder",
        Telefon: "044 807 44 41",
        Mail: "corinne.binder@commodity.ch",
        Yousty: "",
        Internet: "www.commodity.ch",
        PLZ: "8832"
    },
    {
        Firma: "Dachser Spedition AG",
        Adresse: "Althardstrasse 355",
        Ort: "Regensdorf",
        Kontaktperson: "Frau Waltraud Slamanig",
        Telefon: "044 872 11 35",
        Mail: "waltraud.slamanig@dachser.com",
        Yousty: "",
        Internet: "www.dachser.com",
        PLZ: "8105"
    },
    {
        Firma: "Dachser Spedition AG",
        Adresse: "Sägereistrasse 27",
        Ort: "Glattbrugg",
        Kontaktperson: "Frau Vanessa Palumbo",
        Telefon: "061 716 16 02",
        Mail: "vanessa.palumbo@dachser.com",
        Yousty: "",
        Internet: "www.dachser.com",
        PLZ: "8152"
    },
    {
        Firma: "DHL Logistics (Schweiz) AG",
        Adresse: "Schaffhauserstrasse 144",
        Ort: "Kloten",
        Kontaktperson: "Frau Nadia Vogt",
        Telefon: "061 315 95 20",
        Mail: "nadia.vogt@dhl.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12625268-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-kloten-zh-dhl-logistics-schweiz-ag",
        Internet: "www.dhl.com",
        PLZ: "8302"
    },
    {
        Firma: "DSV Air & Sea AG",
        Adresse: "Eichstrasse 50",
        Ort: "Glattbrugg",
        Kontaktperson: "Frau Patricia Russo",
        Telefon: "044 829 40 52",
        Mail: "patricia.russo@dsv.com",
        Yousty: "",
        Internet: "www.dsv.com",
        PLZ: "8152"
    },
    {
        Firma: "Fiege Logistik (Schweiz) AG",
        Adresse: "Schützenmattstrasse 71",
        Ort: "Bülach",
        Kontaktperson: "Frau Sabrina Rolli",
        Telefon: "061 337 43 51",
        Mail: "sabrina.rolli@fiege.com",
        Yousty: "",
        Internet: "www.fiege.com",
        PLZ: "8180"
    },
    {
        Firma: "Fr. Meyer's Sohn (Schweiz) AG",
        Adresse: "Sägereistrasse 24, Postfach 714",
        Ort: "Glattbrugg",
        Kontaktperson: "Frau Selina Taiana",
        Telefon: "044 809 99 34",
        Mail: "selina.taiana@fms-logistics.com",
        Yousty: "",
        Internet: "www.fms-logistics.com",
        PLZ: "8152"
    },
    {
        Firma: "Fracht AG",
        Adresse: "Seidenstrasse 4, Postfach",
        Ort: "Wallisellen",
        Kontaktperson: "Frau Sandra Staub",
        Telefon: "044 308 91 91",
        Mail: "sandra.staub@frachtag-zh.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/10032803-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-wallisellen-8304-zh-fracht-ag-zuerich",
        Internet: "www.frachtag-zh.ch",
        PLZ: "8304"
    },
    {
        Firma: "Fast Trans GmbH",
        Adresse: "Fracht West, Postfach 153",
        Ort: "Zürich-Flughafen",
        Kontaktperson: "Herr Michele Piediscalzi",
        Telefon: "044 804 80 40",
        Mail: "mp@fasttrans.ch",
        Yousty: "",
        Internet: "www.fasttrans.ch",
        PLZ: "8058"
    },
    {
        Firma: "Gebrüder Weiss AG",
        Adresse: "Wibachstrasse 15",
        Ort: "Rümlang",
        Kontaktperson: "Frau Betül Acar",
        Telefon: "058 458 51 72",
        Mail: "betuel.acar@gw-world.com",
        Yousty: "",
        Internet: "www.gw-world.com",
        PLZ: "8153"
    },
    {
        Firma: "General Transport AG",
        Adresse: "Gebäude LUX, Sägereistrasse 29",
        Ort: "Glattbrugg",
        Kontaktperson: "Frau Isabella Bodin",
        Telefon: "044 824 54 11",
        Mail: "isabella.bodin@general-transport.com",
        Yousty: "",
        Internet: "www.general-transport.com",
        PLZ: "8152"
    },
    {
        Firma: "Hellmann Worldwide Logistics AG",
        Adresse: "Steinackerstrasse 28",
        Ort: "Kloten",
        Kontaktperson: "Frau Saumya Thavaseelan",
        Telefon: "044 815 80 03",
        Mail: "saumya.thavaseelan@hellmann.com",
        Yousty: "",
        Internet: "www.hellmann.com",
        PLZ: "8302"
    },
    {
        Firma: "InTraLog Overseas AG",
        Adresse: "Steinackerstrasse 34",
        Ort: "Kloten",
        Kontaktperson: "Frau Yvonne Kummer",
        Telefon: "043 501 36 11",
        Mail: "ykummer@intralog.ch",
        Yousty: "",
        Internet: "www.intralog.ch",
        PLZ: "8302"
    },
    {
        Firma: "JAS Forwarding SA",
        Adresse: "Steinackerstrasse 28",
        Ort: "Kloten",
        Kontaktperson: "Frau Ramona Meli",
        Telefon: "044 815 80 50",
        Mail: "ramona.meli@jas.com",
        Yousty: "",
        Internet: "www.jas.com",
        PLZ: "8302"
    },
    {
        Firma: "Kintetsu World Express (Schweiz) AG",
        Adresse: "Grindelstrasse 9",
        Ort: "Bassersdorf",
        Kontaktperson: "Frau Sandra Kaiser",
        Telefon: "044 838 44 85",
        Mail: "sandra.kasier@kwe.com",
        Yousty: "",
        Internet: "www.kwe.com",
        PLZ: "8303"
    },
    {
        Firma: "Kühne + Nagel AG",
        Adresse: "Feldeggstrasse 5, Postfach 635",
        Ort: "Glattbrugg",
        Kontaktperson: "Herr Nedzad Hukic",
        Telefon: "044 866 81 48",
        Mail: "nedzad.hukic@kuehne-nagel.com",
        Yousty: "",
        Internet: "www.kuehne-nagel.com",
        PLZ: "8152"
    },
    {
        Firma: "Lamprecht Transport AG",
        Adresse: "Embraport 3/Gebäude Z, Postfach",
        Ort: "Embrach",
        Kontaktperson: "Frau Maria del Sol Roldan",
        Telefon: "044 866 21 52",
        Mail: "mariadelsol.roldan@lamprecht.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12468974-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-embrach-zh-lamprecht-transport-ag",
        Internet: "www.lamprecht.ch",
        PLZ: "8424"
    },
    {
        Firma: "Lamprecht Transport AG",
        Adresse: "Fracht West, Postfach 194",
        Ort: "Zürich-Flughafen",
        Kontaktperson: "Frau Stefanie Weber",
        Telefon: "043 816 50 93",
        Mail: "stefanie.weber@lamprecht.ch",
        Yousty: "",
        Internet: "www.lamprecht.ch",
        PLZ: "8058"
    },
    {
        Firma: "Loomis Schweiz AG",
        Adresse: "Steinackerstrasse 49, Postfach",
        Ort: "Kloten",
        Kontaktperson: "Frau Charline Ruchet",
        Telefon: "043 488 92 70",
        Mail: "charline.ruchet@int.loomis.com",
        Yousty: "",
        Internet: "www.int.loomis.com",
        PLZ: "8302"
    },
    {
        Firma: "MyCargoGate AG",
        Adresse: "Grindelstrasse 11",
        Ort: "Bassersdorf",
        Kontaktperson: "Frau Michelle Brunner",
        Telefon: "043 266 21 21",
        Mail: "mbrunner@cargogate.com",
        Yousty: "",
        Internet: "www.cargogate.com",
        PLZ: "8303"
    },
    {
        Firma: "NATCO AG",
        Adresse: "Oberglatterstrasse 35",
        Ort: "Rümlang",
        Kontaktperson: "Frau Rasa Puišytė-Rückert",
        Telefon: "044 818 79 35",
        Mail: "r.puisyte@natco.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12390060-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-ruemlang-zh-natco-ag",
        Internet: "www.natco.ch",
        PLZ: "8153"
    },
    {
        Firma: "NAUTA SA",
        Adresse: "Wanistrasse 1",
        Ort: "Pfungen",
        Kontaktperson: "Frau Franziska Melillo",
        Telefon: "061 337 31 69",
        Mail: "franziska.melillo@nauta.ch",
        Yousty: "",
        Internet: "www.nauta.ch",
        PLZ: "8422"
    },
    {
        Firma: "Nippon Express (Schweiz) AG",
        Adresse: "Grindelstrasse 19",
        Ort: "Bassersdorf",
        Kontaktperson: "Frau Vivianne Haldimann",
        Telefon: "044 838 50 73",
        Mail: "viviane.haldimann@neeur.com",
        Yousty: "",
        Internet: "www.neeur.com",
        PLZ: "8303"
    },
    {
        Firma: "Nova Traffic AG",
        Adresse: "Schaffhauserstrasse 115",
        Ort: "Kloten",
        Kontaktperson: "Frau Miriam Ziltener",
        Telefon: "061 365 96 76",
        Mail: "mziltener@schneider-transport.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12628243-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-kloten-zh-nova-traffic-ltd",
        Internet: "www.schneider-transport.ch",
        PLZ: "8302"
    },
    {
        Firma: "Optimo Logistics / Optimo Services AG",
        Adresse: "Franz-Burckhardt-Strasse 11",
        Ort: "Winterthur",
        Kontaktperson: "Frau Selin Taniyan",
        Telefon: "052 262 46 03",
        Mail: "selin.taniyan@optimo-logistics.com",
        Yousty: "",
        Internet: "www.optimo-logistics.com",
        PLZ: "8404"
    },
    {
        Firma: "Rhenus Logistics AG",
        Adresse: "Fracht West, Postfach 387",
        Ort: "Zürich",
        Kontaktperson: "Frau Alessandra Juchli",
        Telefon: "058 856 94 24",
        Mail: "alessandra.juchli@ch.rhenus.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12671863-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-zuerich-flughafen-zh-rhenus-alpina-ag",
        Internet: "www.ch.rhenus.com",
        PLZ: "8058"
    },
    {
        Firma: "Ruwa Sped AG",
        Adresse: "Fracht West, Postfach 255",
        Ort: "Zürich-Flughafen",
        Kontaktperson: "Herr Hans Lips",
        Telefon: "043 816 31 18",
        Mail: "h.lips@ruwaspeed.ch",
        Yousty: "",
        Internet: "www.ruwaspeed.ch",
        PLZ: "8058"
    },
    {
        Firma: "Schenker Schweiz AG",
        Adresse: "Rautistrasse 77, Postfach",
        Ort: "Zürich",
        Kontaktperson: "Frau Tina Anchora",
        Telefon: "058 589 50 55",
        Mail: "tina.anchora@dbschenker.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/65-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-pfungen-zuerich-zh-schenker-schweiz-ag",
        Internet: "www.dbschenker.com",
        PLZ: "8048"
    },
    {
        Firma: "Schneider + Cie AG",
        Adresse: "Oberfeldstrasse 14",
        Ort: "Kloten",
        Kontaktperson: "Herr Nathalie Fischer",
        Telefon: "044 800 17 35",
        Mail: "nfischer@schneider-transport.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12628237-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-kloten-zh-schneider-cie-ltd",
        Internet: "www.schneider-transport.com",
        PLZ: "8302"
    },
    {
        Firma: "Schneider + Cie AG",
        Adresse: "Hermetschloostrasse 77,\nPostfach 1210",
        Ort: "Zürich",
        Kontaktperson: "Frau Vincenza Russo",
        Telefon: "044 405 27 16",
        Mail: "vrusso@schneider-transport.com",
        Yousty: "",
        Internet: "www.schneider-transport.com",
        PLZ: "8048"
    },
    {
        Firma: "Streck Transport AG",
        Adresse: "Allmendstrasse 9",
        Ort: "Pfungen",
        Kontaktperson: "Frau Linda Schlatter",
        Telefon: "044 866 20 38",
        Mail: "linda.schlatter@streck.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12667744-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-pfungen-zh-streck-transport-ag?uid=2357820",
        Internet: "www.streck.ch",
        PLZ: "8422"
    },
    {
        Firma: "tibbett + britten unique AG",
        Adresse: "Fracht West, Postfach 204",
        Ort: "Zürich-Flughafen",
        Kontaktperson: "Frau Sue Pfyl",
        Telefon: "044 804 20 14",
        Mail: "s.pfyl@tbunique.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12658350-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-zuerich-zh-tibbett-britten-unique-ag?uid=2359194",
        Internet: "www.tbunique.ch",
        PLZ: "8058"
    },
    {
        Firma: "TISA Speditions AG",
        Adresse: "Embraport 8",
        Ort: "Embrach",
        Kontaktperson: "Herr Sven Nickel",
        Telefon: "071 747 33 82",
        Mail: "sven.nickel@tisa.ch",
        Yousty: "",
        Internet: "www.tisa.ch",
        PLZ: "8424"
    },
    {
        Firma: "TRANS SPED AG",
        Adresse: "Embraport 7, Postfach 87",
        Ort: "Embrach",
        Kontaktperson: "Herr Eugen Volkart",
        Telefon: "044 866 28 21",
        Mail: "eugen.volkart@transsped.ch",
        Yousty: "",
        Internet: "www.transsped.ch",
        PLZ: "8424"
    },
    {
        Firma: "Welti-Furrer AG",
        Adresse: "Biologiestrasse 13",
        Ort: "Dielsdorf",
        Kontaktperson: "Frau Melanie Müller",
        Telefon: "044 444 12 56",
        Mail: "melanie.müller@welti-furrer.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/10898668-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-dielsdorf-zh-welti-furrer-ag",
        Internet: "www.welti-furrer.ch",
        PLZ: "8157"
    },
    {
        Firma: "Ziegler (Schweiz) AG",
        Adresse: "Lerzenstrasse 20, Postfach 766",
        Ort: "Dietikon",
        Kontaktperson: "Frau Franziska Vosseler",
        Telefon: "061 815 53 36",
        Mail: "franziska.vosseler@ziegler.ch",
        Yousty: "",
        Internet: "www.ziegler.ch",
        PLZ: "8953"
    },
    {
        Firma: "Bär Zollagentur Schweiz GmbH",
        Adresse: "Bahnhofstrasse 39",
        Ort: "Kreuzlingen",
        Kontaktperson: "Herr Michael Bär",
        Telefon: "071 677 01 03",
        Mail: "michael.baer@translogzoll.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12658354-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-kreuzlingen-tg-baer-zollagentur-schweiz-gmbh?uid=2367682",
        Internet: "www.translogzoll.ch",
        PLZ: "8280"
    },
    {
        Firma: "Dachser Spedition AG Air & Sea",
        Adresse: "Rorschacherstrasse 290 / Postfach 333",
        Ort: "St.",
        Kontaktperson: "Frau Vanessa Palumbo",
        Telefon: "061 716 16 02",
        Mail: "vanessa.palumbo@dachser.com",
        Yousty: "",
        Internet: "www.dachser.com",
        PLZ: "9019"
    },
    {
        Firma: "",
        Adresse: "Heldaustrasse 66",
        Ort: "Buchs",
        Kontaktperson: "Frau Franziska Rupf-Lohr",
        Telefon: "081 755 12 98",
        Mail: "franziska.rupf-lohr@dhl.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12625269-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-buchs-sg-dhl-logistics-schweiz-ag",
        Internet: "www.dhl.com",
        PLZ: "9470"
    },
    {
        Firma: "DSV Air & Sea AG",
        Adresse: "Schuppisstrasse 3",
        Ort: "St.Gallen",
        Kontaktperson: "Frau Patricia Russo",
        Telefon: "044 829 40 52",
        Mail: "patricia.russo@dsv.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/65-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-pfungen-zuerich-zh-schenker-schweiz-ag",
        Internet: "www.dsv.com",
        PLZ: "9016"
    },
    {
        Firma: "Gebrüder Weiss AG",
        Adresse: "Werftstrasse 1",
        Ort: "Altenrhein",
        Kontaktperson: "Frau Dusanka Geldmacher",
        Telefon: "058 458 54 05",
        Mail: "dusanka.geldmacher@gw-world.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/1359-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-altenrhein-sg-gebrueder-weiss-ag",
        Internet: "www.gw-world.com",
        PLZ: "9423"
    },
    {
        Firma: "Hoco International AG",
        Adresse: "Piccardstrasse 13",
        Ort: "St.",
        Kontaktperson: "Herr Antonio Fiorenza",
        Telefon: "071 313 91 41",
        Mail: "antonio.fiorenza@hoco-int.ch",
        Yousty: "",
        Internet: "www.hoco-int.ch",
        PLZ: "9015"
    },
    {
        Firma: "JCL Logistics Switzerland AG",
        Adresse: "Neugrütstrasse 3",
        Ort: "St.",
        Kontaktperson: "Frau Sabrina Rohden",
        Telefon: "071 747 43 27",
        Mail: "sabrina.rhoden@jcl-logistics.com",
        Yousty: "",
        Internet: "www.jcl-logistics.com",
        PLZ: "9430"
    },
    {
        Firma: "Lamprecht Transport AG",
        Adresse: "Oberstrasse 149",
        Ort: "St.",
        Kontaktperson: "Herr Markus Keller",
        Telefon: "071 272 13 53",
        Mail: "markus.keller@lamprecht.ch",
        Yousty: "",
        Internet: "www.lamprecht.ch",
        PLZ: "9001"
    },
    {
        Firma: "Lebert AG",
        Adresse: "Tägerwilerstrasse 1",
        Ort: "Kreuzlingen",
        Kontaktperson: "Frau Franziska Greim-Schaad",
        Telefon: "071 677 22 30",
        Mail: "franziska.greim-schaad@lebert.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12634501-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-kreuzlingen-tg-lebert-ag",
        Internet: "www.lebert.com",
        PLZ: "8280"
    },
    {
        Firma: "NTG Gondrand International AG",
        Adresse: "Friedrichshafnerstrasse 51",
        Ort: "Romanshorn",
        Kontaktperson: "Herr Peter Schmitz",
        Telefon: "071 466 72 54",
        Mail: "psc@ntgroad.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12658353-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-romanshorn-tg-ntg-road-ag?uid=2391242",
        Internet: "www.ntgroad.com",
        PLZ: "8590"
    },
    {
        Firma: "Seiler Logistics AG",
        Adresse: "Scheidwegstrasse 18b",
        Ort: "St.Gallen",
        Kontaktperson: "Frau Alexandra Trummer",
        Telefon: "071 246 00 67",
        Mail: "alex@seilo.ch",
        Yousty: "",
        Internet: "www.seilo.ch",
        PLZ: "9000"
    },
    {
        Firma: "Sieber Transport AG",
        Adresse: "Musterplatzstrasse 5",
        Ort: "Berneck",
        Kontaktperson: "Frau Jeannine Merten",
        Telefon: "071 747 66 00",
        Mail: "jeannine.merten@sieber.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12648226-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-berneck-sg-sieber-transport-ag",
        Internet: "www.sieber.ch",
        PLZ: "9442"
    },
    {
        Firma: "TISA Speditions AG",
        Adresse: "Unterlettenstrasse 11",
        Ort: "Widnau",
        Kontaktperson: "Herr Dieter Fiel",
        Telefon: "071 747 33 75",
        Mail: "dieter.fiel@tisa.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12617133-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-widnau-sg-tisa-speditions-ag",
        Internet: "www.tisa.ch",
        PLZ: "9443"
    },
    {
        Firma: "TRALOG AG",
        Adresse: "Tägermoostrasse 3",
        Ort: "Kreuzlingen",
        Kontaktperson: "Frau Daria Ammann",
        Telefon: "071 677 60 90",
        Mail: "daria.ammann@tralog.ch",
        Yousty: "",
        Internet: "www.tralog.ch",
        PLZ: "8082"
    },
    {
        Firma: "World of Green Logistics AG",
        Adresse: "Wildenaustrasse 22",
        Ort: "Diepoldsau",
        Kontaktperson: "Herr Marcel Burtscher",
        Telefon: "071 733 77 02",
        Mail: "marcel.butscher@worldofgreen.ch",
        Yousty: "",
        Internet: "www.worldofgreen.ch",
        PLZ: "9444"
    },
    {
        Firma: "Ziegler Schweiz AG",
        Adresse: "Bionstrasse 5",
        Ort: "St.",
        Kontaktperson: "Herr Angelo Melillo",
        Telefon: "071 311 13 63",
        Mail: "angelo.melillo@ziegler.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/9439513-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-st-gallen-sg-ziegler-schweiz-ag",
        Internet: "www.ziegler.ch",
        PLZ: "9015"
    },
    {
        Firma: "Balimbex AG",
        Adresse: "Bietingerstrasse 98a",
        Ort: "Thayngen",
        Kontaktperson: "Herr Mehmet Ferreira Dinc",
        Telefon: "052 649 24 24",
        Mail: "mehmet.ferreira@balimbex.ch",
        Yousty: "",
        Internet: "www.balimbex.ch",
        PLZ: "8240"
    },
    {
        Firma: "DSV Logistics SA",
        Adresse: "Ernst Hombergerstrasse 5",
        Ort: "Schaffhausen",
        Kontaktperson: "Herr Valid Karisik",
        Telefon: "052 644 01 77",
        Mail: "valid.karisik@dsv.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12665619-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-schaffhausen-sh-dsv-logistics-sa?uid=2360380",
        Internet: "www.dsv.com",
        PLZ: "8207"
    },
    {
        Firma: "Hofstetter + Co AG",
        Adresse: "Ebnatstrasse 125",
        Ort: "Schaffhausen",
        Kontaktperson: "Frau Rena Gökyilmaz",
        Telefon: "052 644 19 42",
        Mail: "rena.geoklyilmaz@hocosped.ch",
        Yousty: "",
        Internet: "www.hocosped.ch",
        PLZ: "8200"
    },
    {
        Firma: "Holenstein AG",
        Adresse: "Ernst Hombergerstrasse 5",
        Ort: "Schaffhausen",
        Kontaktperson: "Frau Deborah Wagner",
        Telefon: "052 644 80 07",
        Mail: "deborah.wagner@holenstein-transport.ch",
        Yousty: "",
        Internet: "www.holenstein-transport.ch",
        PLZ: "8207"
    },
    {
        Firma: "JCL Logistics Switzerland AG",
        Adresse: "Stammlerbüelstrasse 9",
        Ort: "Thayngen",
        Kontaktperson: "Herr Pascal Baumgartner",
        Telefon: "052 645 31 14",
        Mail: "pascal.baumgartner @jcl-logistics.com",
        Yousty: "",
        Internet: "www.jcl-logistics.com",
        PLZ: "8240"
    },
    {
        Firma: "Kühne + Nagel AG",
        Adresse: "Erlenstrasse 3",
        Ort: "Thayngen",
        Kontaktperson: "Frau Simone Durban",
        Telefon: "052 644 50 85",
        Mail: "simone.durban@kuehne-nagel.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/3846898-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-opfikon-zh-kuehne-nagel-ag",
        Internet: "www.kuehne-nagel.com",
        PLZ: "8240"
    },
    {
        Firma: "Lamprecht AG",
        Adresse: "Lagerhaus Petersburg",
        Ort: "Ramsen",
        Kontaktperson: "Frau Yvonne Stubbe",
        Telefon: "052 742 80 73",
        Mail: "stu@lamprecht.ch",
        Yousty: "",
        Internet: "www.lamprecht.ch",
        PLZ: "8262"
    },
    {
        Firma: "LOG AG",
        Adresse: "Trasadingerstrasse 5",
        Ort: "Guntmadingen",
        Kontaktperson: "Herr Christian Landolt",
        Telefon: "052 645 40 17",
        Mail: "c.landolt@log-ag.swiss",
        Yousty: "",
        Internet: "www.log-ag.swiss",
        PLZ: "8223"
    },
    {
        Firma: "M+R Spedag Group AG",
        Adresse: "Gennersbrunnerstrasse 68",
        Ort: "Schaffhausen",
        Kontaktperson: "Frau Birgit Häringer",
        Telefon: "058 677 18 29",
        Mail: "birgit.haeringer@mrspedag.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12665636-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-schaffhausen-sh-m-r-spedag-group-ag?uid=2362352",
        Internet: "www.mrspedag.com",
        PLZ: "8207"
    },
    {
        Firma: "Rhenus Contract Logistics AG",
        Adresse: "Solenbergstrasse 7",
        Ort: "Schaffhausen",
        Kontaktperson: "Herr Norman Ragg",
        Telefon: "052 569 36 84",
        Mail: "norman.ragg@ch.rhenus.com",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12671865-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-schaffhausen-sh-rhenus-alpina-ag",
        Internet: "www.ch.rhenus.com",
        PLZ: "8207"
    },
    {
        Firma: "SG Spedition GmbH",
        Adresse: "Anthoptstrasse 4",
        Ort: "Beringen",
        Kontaktperson: "Herr Philippe Rüfli",
        Telefon: "052 644 00 61",
        Mail: "ruefli@sg-spedition.ch",
        Yousty: "",
        Internet: "www.sg-spedition.ch",
        PLZ: "8222"
    },
    {
        Firma: "Spedifa GmbH",
        Adresse: "Bietingerstrasse 98a",
        Ort: "Thayngen",
        Kontaktperson: "Frau Nicole Grin",
        Telefon: "052 645 03 10",
        Mail: "n.grin@spedifa.ch",
        Yousty: "",
        Internet: "www.spedifa.ch",
        PLZ: "8240"
    },
    {
        Firma: "TLI TransLog Transport AG",
        Adresse: "Stammlerbüelstrasse 9",
        Ort: "Thayngen",
        Kontaktperson: "Frau Jessica Flubacher",
        Telefon: "052 551 06 77",
        Mail: "j.flubacher@tli-translog.ch",
        Yousty: "https://www.yousty.ch/de-CH/lehrstellen/profile/12665632-kaufmann-frau-kv-efz-internationale-speditionslogistik-isl-thayngen-sh-tli-translog-transport-ag?uid=2365603",
        Internet: "www.tli-translog.ch",
        PLZ: "8240"
    }
]

// const fix = OSTSCHWEIZ.map(o => {
//     const [PLZ, Ort] = o.Ort.split(' ')
//     console.log(PLZ)
//     console.log(Ort)
//     return {...o, PLZ, Ort}
// })
//
// console.log(fix)

